HOMEWORK
Data_Analysis_1
Numpy & Pandas
ERTAN PULAT

In [1]:
import numpy as np

1.Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.
Tek boyutlu dizilere Vektör
Çok boyutlu dizilere Matris denir.

In [3]:
#2.10 elemanli bir listeden NumPy Array’i olusturunuz.
numpy_array = np.array([0,1,2,3,4,5,6,7,8,9])

In [4]:
#3.Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
#4.Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10),dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
#5.Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.full((10,10),9,dtype=int)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [12]:
# 6. 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [8]:
# 7. -1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace(-1,1,30)

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

In [13]:
# 8. 0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.random.randint(0,30,(5,6))

array([[19, 17, 13,  1,  6, 23],
       [24, 18, 24, 22, 27, 25],
       [ 7, 11, 26, 12, 26, 15],
       [25, 19,  0,  2, 21, 20],
       [ 1, 15, 12, 25, 11, 15]])

In [14]:
# 9. Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
'''10. 0 ile 10 arasinda 5x10’lik bir matris olusturun.
(integer) ve bu matrisin; • eleman sayisini •
boyut bilgisini/sayisini • satir X sutun bilgisini
• veri tipini numpy metodlariyla yazdiriniz.'''

a = np.random.randint(0,10,(5,10),dtype=int)
print(a)
#a.size  #eleman sayısı
#a.ndim 
#a.shape
#a.dtype

[[5 1 3 8 6 6 5 5 6 7]
 [4 7 4 6 5 2 7 2 2 0]
 [6 3 5 9 6 0 6 0 8 6]
 [0 7 6 4 0 5 8 3 2 6]
 [6 5 3 4 7 4 6 9 8 8]]


In [18]:
a.size

50

In [19]:
a.ndim

2

In [20]:
a.shape

(5, 10)

In [21]:
a.dtype

dtype('int32')

In [22]:
'''11. 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz.
(3 boyutlu bir matris olusturulacak)'''
np.random.randint(0,10,(3,4,7))

array([[[4, 2, 7, 4, 5, 2, 9],
        [5, 7, 5, 6, 3, 6, 5],
        [9, 4, 9, 5, 1, 7, 1],
        [2, 7, 4, 3, 4, 6, 8]],

       [[7, 9, 4, 2, 8, 5, 2],
        [2, 7, 3, 4, 5, 8, 4],
        [2, 3, 4, 0, 8, 0, 0],
        [3, 1, 8, 7, 2, 1, 5]],

       [[0, 2, 5, 9, 0, 4, 6],
        [3, 6, 9, 4, 1, 6, 4],
        [8, 9, 7, 8, 4, 4, 7],
        [7, 5, 3, 5, 8, 5, 7]]])

In [23]:
# 12.Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)
a = np.array([1,2,3,4])
print(a)
print(a.ndim)
b = a.reshape(2,2)
print(b)
print(b.ndim)

[1 2 3 4]
1
[[1 2]
 [3 4]]
2


In [24]:
# 13. 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
x = np.array([1,2,3])
y = np.array([5,6,7,8])
z = np.array([9,10,11,12])
t = np.array([13,14,15,16])
np.concatenate([x,y,z,t])

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

14.2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [2]:
import numpy as np

In [9]:
v=np.array([[4],[5]])
m=np.array([[6,7,8],[9,10,11]])
print(v)
print(m)
vm=np.concatenate([v,m],axis=1)
vm


[[4]
 [5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 4,  6,  7,  8],
       [ 5,  9, 10, 11]])

15.Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

axis hangi bazda işlem yapacağınızı açıklar.
eğer axis 0 olursa satır bazında 
axis 1 olursa sütun bazında işlem yapacağınız anlamına gelir.

In [ ]:
#16. Farkli boyutlardaki arraylari satır ve sutun bazli ayri ayri birlestiriniz.


In [14]:
#17.10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 
x = np.array([0,1,2,3,4,5,6,7,8,9])
np.split(x, [2,3,4,5])


[array([0, 1]), array([2]), array([3]), array([4]), array([5, 6, 7, 8, 9])]

In [28]:
#18. Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan
# sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.
a = np.random.randint(0,10,size=10)
a

array([2, 3, 7, 6, 3, 7, 3, 2, 9, 4])

In [29]:
np.sort(a)

array([2, 2, 3, 3, 3, 4, 6, 7, 7, 9])

In [30]:
#19.20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.
b = np.random.randint(20,size=20)
b

array([ 1,  0,  9,  0,  4,  9, 13, 10, 17, 12, 15, 12,  0,  2,  4, 19,  2,
        1, 18,  0])

In [32]:
b[3]

10

In [33]:
b[5]

9

In [34]:
b[7]

10

In [35]:
#20.10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
e = np.random.randint(10,size = 10)
e

array([9, 5, 3, 9, 6, 5, 2, 4, 0, 2])

In [36]:
e[4] = 99
e

array([ 9,  5,  3,  9, 99,  5,  2,  4,  0,  2])

21.“Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

“Diagonal (köşegen) Matrix” : Bir kare matriste asal köşegen üzerindeki elemanların dışında kalan tüm elemanlar sıfır ise bu matrise köşegen matris denir.
“Trace of Matrix” :  İlkköşegen üzerindeki ögelerin toplamıdır.Ana köşegenindeki (sol üstten sağ alta) elemanların toplamı olarak tanımlanır.

In [38]:
#22.5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)
a = np.random.randint(0,30,(5,5))
a

array([[20, 22,  2, 11,  0],
       [24,  9, 17, 15, 28],
       [26,  6, 12, 19, 11],
       [ 6, 20,  4, 17, 19],
       [21, 16, 18,  3,  7]])

In [39]:
a.diagonal()

array([20,  9, 12, 17,  7])

In [41]:
#23.10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
a[3:]

array([13, 14, 15, 16, 17, 18, 19])

#24.
'''
10X10 luk bir matris olusturunuz ve ; • 3.satir ve 5.sutuna ulasiniz. • 5.sutunun tum satirlarina ulasiniz. 
• Tum sutunlarin 2.satirlarina ulasiniz. • tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz. 
• satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
• satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz. 
•sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
• 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

'''

In [46]:
e = np.random.randint(100,size=(10,10))
e

array([[19, 70, 58, 68, 65,  6,  4, 83, 68,  3],
       [98, 85, 86,  8, 58, 34, 98, 92,  6, 61],
       [16, 48, 10, 36, 54, 63, 64, 37, 14, 80],
       [50, 57, 88, 98, 14, 85, 22, 15, 62, 51],
       [82, 21,  9, 82, 76, 37, 40, 51, 85, 92],
       [ 1,  9,  8, 72, 68, 45, 53, 77, 80, 43],
       [17,  9, 16, 73, 62, 74, 90,  5, 24, 14],
       [ 0,  0, 59,  3,  2, 55, 79, 97, 29, 92],
       [76, 97, 54, 28, 73, 98, 73, 43, 13, 62],
       [30, 35, 93, 80, 18, 87, 67, 87, 51, 85]])

In [47]:
#3.satir ve 5.sutuna ulasiniz
e[3:,5]

array([85, 37, 45, 74, 55, 98, 87])

In [48]:
#5.sutunun tum satirlarina ulasiniz. 
e[:,5]

array([ 6, 34, 63, 85, 37, 45, 74, 55, 98, 87])

In [50]:
# Tum sutunlarin 2.satirlarina ulasiniz.
e[2,:]

array([16, 48, 10, 36, 54, 63, 64, 37, 14, 80])

In [51]:
#tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
e[2:7,]

array([[16, 48, 10, 36, 54, 63, 64, 37, 14, 80],
       [50, 57, 88, 98, 14, 85, 22, 15, 62, 51],
       [82, 21,  9, 82, 76, 37, 40, 51, 85, 92],
       [ 1,  9,  8, 72, 68, 45, 53, 77, 80, 43],
       [17,  9, 16, 73, 62, 74, 90,  5, 24, 14]])

In [52]:
#satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz. 
e[2:5,3:7]

array([[36, 54, 63, 64],
       [98, 14, 85, 22],
       [82, 76, 37, 40]])

In [53]:
#satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
e[5:,:4]

array([[ 1,  9,  8, 72],
       [17,  9, 16, 73],
       [ 0,  0, 59,  3],
       [76, 97, 54, 28],
       [30, 35, 93, 80]])

In [54]:
#sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
e[:,[3,6,9]]

array([[68,  4,  3],
       [ 8, 98, 61],
       [36, 64, 80],
       [98, 22, 51],
       [82, 40, 92],
       [72, 53, 43],
       [73, 90, 14],
       [ 3, 79, 92],
       [28, 73, 62],
       [80, 67, 85]])

In [55]:
#5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.
e[5,5] = 1991
e

array([[  19,   70,   58,   68,   65,    6,    4,   83,   68,    3],
       [  98,   85,   86,    8,   58,   34,   98,   92,    6,   61],
       [  16,   48,   10,   36,   54,   63,   64,   37,   14,   80],
       [  50,   57,   88,   98,   14,   85,   22,   15,   62,   51],
       [  82,   21,    9,   82,   76,   37,   40,   51,   85,   92],
       [   1,    9,    8,   72,   68, 1991,   53,   77,   80,   43],
       [  17,    9,   16,   73,   62,   74,   90,    5,   24,   14],
       [   0,    0,   59,    3,    2,   55,   79,   97,   29,   92],
       [  76,   97,   54,   28,   73,   98,   73,   43,   13,   62],
       [  30,   35,   93,   80,   18,   87,   67,   87,   51,   85]])

25.
0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin; 
• 20 den buyuk olan kac deger var. 
• 30’dan kucuk kac deger var 
• icerisinde 33 gecen kac deger var 
• olusturulan arrayin tum elemanlarini 5 ile carpin. 
• olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [56]:
e = np.arange(0,50,5)
e

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [59]:
e[e>20]

array([25, 30, 35, 40, 45])

In [60]:
e[e<30]

array([ 0,  5, 10, 15, 20, 25])

In [62]:
e[e == 33]

array([], dtype=int32)

In [63]:
e*5

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

In [64]:
e%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

26.
0 ile 1 arasinda 50 elamanli bir array olusturunuz ve; 
• orlamasini aliniz. • standart sapmasini aliniz. • varyansini aliniz. • median’ini aliniz. • en kucuk degeri bulunuz.
• en buyuk degeri bulunuz.

Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.

In [69]:
e = np.linspace(0,1,50)
e

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

np.mean(e)
np.std(e)
np.var(e)
np.median(e)
np.min(e)
np.max(e)

In [70]:
np.mean(e)

0.5

In [71]:
np.std(e)

0.2945075446869757

In [72]:
np.var(e)

0.086734693877551

In [74]:
np.median(e)

0.5

In [75]:
np.min(e)

0.0

In [76]:
np.max(e)

1.0

Master odev ; Bir dongu icerisinde random olacak sekilde iki tane 20x20’luk matris uretin ve bu matrislerin farklarini alin. Ve fark matrisinin diagonali, -0.1 ile 0.1 arasinda olana kadar bu islemi tekrarlayin. Istenilen matris bulundugunda program dursun ve toplam kac dongunun kuruldugunu, ne kadar sure icinde buldugunu ve istenilen matrisi print ile birlikte ekrana yazdiriniz... Tavsiye: 20 x 20 luk matrisin bulunmasi saatler surebilir. Bu yuzden algoritmanizin dogrulugunu test etmek icin once 4x4, 5x5 gibi kucuk matrislerde deneyebilirsiniz. Ve matris sayisisini arttirarak en son 20x20 u deneyebilirsiniz.